### ISSUE TITLE
Fork/Force support

### ISSUE THREAD

**Issue by jayvdb** [lpenz/ghaction-version-gen#2]
I dont know what this would entail, but ...

I am trying to build my own https://github.com/jayvdb/ghaction-cmake , and want to do minimal changes to the CI.

`steps.version.outputs.version_docker_ci` is `'null'` .  The easiest way to get past this is to remove that check in the CI, but maybe we can find a better way of doing this.

Perhaps some alternative mode is activated when a fork is detected.  Or some inputs that allow the outputs to be overriden as necessary.

**Comment by lpenz** [comment]
We definitely want to support forks!
Can you point me to the failed execution? I couldn't find it.

**Comment by jayvdb** [comment]
I didnt have a failure per se ; the docker image wasnt uploaded because `steps.version.outputs.version_docker_ci` is `null` on my branch pushes, and the docker upload action doesnt push when that happens
https://github.com/jayvdb/ghaction-cmake/runs/4343246485?check_suite_focus=true#step:8:5382

**Comment by lpenz** [comment]
It should push when the tag is in the format `v1.2.3`

**Comment by jayvdb** [comment]
I would prefer to be avoiding real versions, as my fork is doing various hacks on top of your versions.
Perhaps a env variable like 'DOCKERHUB_TAG_USING_BRANCH_NAME'...?

**Comment by lpenz** [comment]
That's a good point.

Also, it's worth pointing out that it's also not null when you push to the `main` or `master` branches. In those cases, gets the `latest` string as a value.

**Comment by lpenz** [comment]
I think I understand the issue now, and I definitely see value in the env var suggestion

**Comment by jayvdb** [comment]
#4 doesnt really match what I had in mind with `DOCKERHUB_TAG_USING_BRANCH_NAME` which I could set once and forget, and it would create or overwrite a tag for each branch I pushed. With #4 I would need to change envvars now to specify different tags manually for each branch - I might as well just update yml.  The problem with both is I occasionally forget to update the intended tag, and overwrite an existing tag for a different branch.
